const path = require("node:path");

const INLINE_RUST_COMMAND_ID = "thebe.openInlineRustView";

function resolveInlineRustView({
  documentPath,
  workspaceFolders,
  source,
  selectionStartOffset,
  selectionEndOffset,
}) {
  const targetPath = resolveGeneratedServerMirrorPath({ documentPath, workspaceFolders });
  if (!targetPath) {
    return { ok: false, reason: "not-route" };
  }

  const scriptBlock = findRustSetupBlock(source);
  if (!scriptBlock) {
    return { ok: false, reason: "no-script" };
  }

  const routePath = resolveRoutePathPattern({ documentPath, workspaceFolders });
  const prefix = buildInlineRustPrefix({ routePath });
  const suffix = buildInlineRustSuffix();
  return {
    ok: true,
    targetPath,
    sourcePath: documentPath,
    sourceText: source,
    content: prefix + scriptBlock.content + suffix,
    prefixLength: prefix.length,
    scriptStartOffset: scriptBlock.start,
    scriptEndOffset: scriptBlock.end,
    selectionStartOffset: mapSourceOffsetToInlineOffset({
      sourceOffset: selectionStartOffset,
      scriptBlock,
      prefixLength: prefix.length,
    }),
    selectionEndOffset: mapSourceOffsetToInlineOffset({
      sourceOffset: selectionEndOffset,
      scriptBlock,
      prefixLength: prefix.length,
    }),
  };
}

function resolveGeneratedServerMirrorPath({ documentPath, workspaceFolders }) {
  const routeEntry = resolveRouteSourceEntry({ documentPath, workspaceFolders });
  if (!routeEntry) {
    return null;
  }

  return path.join(
    routeEntry.workspaceFolder,
    ".thebe",
    "server",
    "routes",
    routeEntry.relativePath.slice(0, -4) + ".rs",
  );
}

function resolveRouteSourceEntry({ documentPath, workspaceFolders }) {
  if (typeof documentPath !== "string" || documentPath.length === 0) {
    return null;
  }

  for (const workspaceFolder of workspaceFolders ?? []) {
    if (typeof workspaceFolder !== "string" || workspaceFolder.length === 0) {
      continue;
    }

    const routesDir = path.join(workspaceFolder, "src", "routes");
    const relativePath = path.relative(routesDir, documentPath);
    if (
      relativePath.length === 0
      || relativePath.startsWith("..")
      || path.isAbsolute(relativePath)
      || path.extname(relativePath) !== ".trs"
      || path.basename(relativePath).startsWith("_")
    ) {
      continue;
    }

    return {
      workspaceFolder,
      relativePath,
    };
  }

  return null;
}

function resolveRoutePathPattern({ documentPath, workspaceFolders }) {
  const routeEntry = resolveRouteSourceEntry({ documentPath, workspaceFolders });
  if (!routeEntry) {
    return "/";
  }

  const normalized = routeEntry.relativePath.split(path.sep).join("/");
  const stem = normalized.slice(0, -4);
  const segments = stem.split("/");
  if (segments.at(-1) === "index") {
    segments.pop();
  }

  const routeSegments = segments
    .filter((segment) => segment.length > 0)
    .map((segment) => {
      if (segment.startsWith("[") && segment.endsWith("]") && segment.length > 2) {
        return `{${segment.slice(1, -1)}}`;
      }
      return segment;
    });
  return routeSegments.length === 0 ? "/" : `/${routeSegments.join("/")}`;
}

function buildInlineRustPrefix({ routePath }) {
  const lines = [
    "// AUTOGENERATED by thebe — inline Rust view",
    "#![allow(unused_attributes, dead_code, private_interfaces)]",
    `const __ROUTE_PATH: &str = ${JSON.stringify(routePath)};`,
    "",
  ];
  return `${lines.join("\n")}\n`;
}

function buildInlineRustSuffix() {
  const lines = [
    "",
    "type __ThebeResponse = Result<axum::response::Html<String>, axum::response::Response>;",
    "",
    "async fn __thebe_render_handler() -> __ThebeResponse {",
    "    todo!(\"inline Rust view render wrapper\");",
    "}",
    "",
    "pub fn router<S>() -> axum::Router<S>",
    "where",
    "    S: Clone + Send + Sync + 'static,",
    "{",
    "    axum::Router::<S>::new().route(",
    "        __ROUTE_PATH,",
    "        axum::routing::get(__thebe_render_handler),",
    "    )",
    "}",
    "",
  ];
  return lines.join("\n");
}

function mapSourceOffsetToInlineOffset({ sourceOffset, scriptBlock, prefixLength }) {
  if (typeof sourceOffset !== "number") {
    return prefixLength;
  }

  const clampedOffset = Math.min(Math.max(sourceOffset, scriptBlock.start), scriptBlock.end);
  return prefixLength + clampedOffset - scriptBlock.start;
}

function mapInlineOffsetToSourceOffset({ inlineOffset, view }) {
  if (typeof inlineOffset !== "number") {
    return null;
  }

  const contentLength = view.scriptEndOffset - view.scriptStartOffset;
  if (inlineOffset < view.prefixLength || inlineOffset > view.prefixLength + contentLength) {
    return null;
  }

  return view.scriptStartOffset + inlineOffset - view.prefixLength;
}

function resolveInlineRustSourceRange({ view, startOffset, endOffset }) {
  const sourceStartOffset = mapInlineOffsetToSourceOffset({ inlineOffset: startOffset, view });
  const sourceEndOffset = mapInlineOffsetToSourceOffset({ inlineOffset: endOffset, view });
  if (sourceStartOffset === null || sourceEndOffset === null) {
    return null;
  }

  return {
    startOffset: sourceStartOffset,
    endOffset: sourceEndOffset,
  };
}

function resolveInlineRustSourcePositionRange({ view, startOffset, endOffset }) {
  if (typeof view.sourceText !== "string") {
    return null;
  }

  const sourceRange = resolveInlineRustSourceRange({ view, startOffset, endOffset });
  if (!sourceRange) {
    return null;
  }

  return {
    start: positionAtOffset(view.sourceText, sourceRange.startOffset),
    end: positionAtOffset(view.sourceText, sourceRange.endOffset),
  };
}

function positionAtOffset(source, offset) {
  const targetOffset = Math.min(Math.max(offset, 0), source.length);
  let line = 0;
  let character = 0;

  for (let index = 0; index < targetOffset; index += 1) {
    const code = source.charCodeAt(index);
    if (code === 13) {
      if (source.charCodeAt(index + 1) === 10) {
        index += 1;
      }
      line += 1;
      character = 0;
      continue;
    }

    if (code === 10) {
      line += 1;
      character = 0;
      continue;
    }

    character += 1;
  }

  return { line, character };
}

function findRustSetupBlock(source) {
  if (typeof source !== "string" || source.length === 0) {
    return null;
  }

  let offset = 0;
  while (offset < source.length) {
    const openTagStart = source.indexOf("<script", offset);
    if (openTagStart === -1) {
      return null;
    }

    const openTagEnd = findTagEnd(source, openTagStart + 7);
    if (openTagEnd === -1) {
      return null;
    }

    const attrs = parseTagAttributes(source.slice(openTagStart, openTagEnd + 1));
    if (Object.hasOwn(attrs, "setup")) {
      const contentStart = openTagEnd + 1;
      const closeTagStart = source.indexOf("</script>", contentStart);
      if (closeTagStart === -1) {
        return null;
      }

      return {
        start: contentStart,
        end: closeTagStart,
        content: source.slice(contentStart, closeTagStart),
      };
    }

    offset = openTagEnd + 1;
  }

  return null;
}

function findTagEnd(source, startOffset) {
  let quote = null;
  for (let index = startOffset; index < source.length; index += 1) {
    const char = source[index];
    if (quote) {
      if (char === quote) {
        quote = null;
      }
      continue;
    }

    if (char === '"' || char === "'") {
      quote = char;
      continue;
    }

    if (char === ">") {
      return index;
    }
  }

  return -1;
}

function parseTagAttributes(tagSource) {
  const attrs = Object.create(null);
  let offset = tagSource.indexOf("script") + 6;
  while (offset < tagSource.length) {
    offset = skipWhitespace(tagSource, offset);
    const char = tagSource[offset];
    if (!char || char === ">" || char === "/") {
      break;
    }

    const nameStart = offset;
    while (offset < tagSource.length) {
      const current = tagSource[offset];
      if (/\s|=|>|\//.test(current)) {
        break;
      }
      offset += 1;
    }

    const name = tagSource.slice(nameStart, offset).toLowerCase();
    offset = skipWhitespace(tagSource, offset);
    let value = true;
    if (tagSource[offset] === "=") {
      offset += 1;
      offset = skipWhitespace(tagSource, offset);
      value = readAttributeValue(tagSource, offset);
      offset = value.nextOffset;
      value = value.value;
    }

    attrs[name] = typeof value === "string" ? value.toLowerCase() : value;
  }

  return attrs;
}

function readAttributeValue(source, startOffset) {
  const quote = source[startOffset];
  if (quote === '"' || quote === "'") {
    let offset = startOffset + 1;
    while (offset < source.length && source[offset] !== quote) {
      offset += 1;
    }
    return {
      value: source.slice(startOffset + 1, offset),
      nextOffset: offset + 1,
    };
  }

  let offset = startOffset;
  while (offset < source.length && !/\s|>/.test(source[offset])) {
    offset += 1;
  }
  return {
    value: source.slice(startOffset, offset),
    nextOffset: offset,
  };
}

function skipWhitespace(source, startOffset) {
  let offset = startOffset;
  while (offset < source.length && /\s/.test(source[offset])) {
    offset += 1;
  }
  return offset;
}

module.exports = {
  INLINE_RUST_COMMAND_ID,
  resolveGeneratedServerMirrorPath,
  resolveInlineRustSourcePositionRange,
  resolveInlineRustSourceRange,
  resolveInlineRustView,
};
