const path = require("node:path");

const INLINE_RUST_COMMAND_ID = "thebe.openInlineRustView";

function resolveInlineRustView({
  documentPath,
  workspaceFolders,
  source,
  selectionStartOffset,
  selectionEndOffset,
}) {
  const targetPath = resolveGeneratedServerMirrorPath({ documentPath, workspaceFolders });
  if (!targetPath) {
    return { ok: false, reason: "not-route" };
  }

  const scriptBlock = findRustSetupBlock(source);
  if (!scriptBlock) {
    return { ok: false, reason: "no-script" };
  }

  const routePath = resolveRoutePathPattern({ documentPath, workspaceFolders });
  const prefix = buildInlineRustPrefix({ routePath });
  const suffix = buildInlineRustSuffix();
  return {
    ok: true,
    targetPath,
    sourcePath: documentPath,
    sourceText: source,
    content: prefix + scriptBlock.content + suffix,
    prefixLength: prefix.length,
    scriptStartOffset: scriptBlock.start,
    scriptEndOffset: scriptBlock.end,
    selectionStartOffset: mapSourceOffsetToInlineOffset({
      sourceOffset: selectionStartOffset,
      scriptBlock,
      prefixLength: prefix.length,
    }),
    selectionEndOffset: mapSourceOffsetToInlineOffset({
      sourceOffset: selectionEndOffset,
      scriptBlock,
      prefixLength: prefix.length,
    }),
  };
}

function resolveGeneratedServerMirrorPath({ documentPath, workspaceFolders }) {
  const routeEntry = resolveRouteSourceEntry({ documentPath, workspaceFolders });
  if (!routeEntry) {
    return null;
  }

  return path.join(
    routeEntry.workspaceFolder,
    ".thebe",
    "server",
    "routes",
    routeEntry.relativePath.slice(0, -4) + ".rs",
  );
}

function resolveRouteSourceEntry({ documentPath, workspaceFolders }) {
  if (typeof documentPath !== "string" || documentPath.length === 0) {
    return null;
  }

  for (const workspaceFolder of workspaceFolders ?? []) {
    if (typeof workspaceFolder !== "string" || workspaceFolder.length === 0) {
      continue;
    }

    const routesDir = path.join(workspaceFolder, "src", "routes");
    const relativePath = path.relative(routesDir, documentPath);
    if (
      relativePath.length === 0
      || relativePath.startsWith("..")
      || path.isAbsolute(relativePath)
      || path.extname(relativePath) !== ".trs"
      || path.basename(relativePath).startsWith("_")
    ) {
      continue;
    }

    return {
      workspaceFolder,
      relativePath,
    };
  }

  return null;
}

function resolveRoutePathPattern({ documentPath, workspaceFolders }) {
  const routeEntry = resolveRouteSourceEntry({ documentPath, workspaceFolders });
  if (!routeEntry) {
    return "/";
  }

  const normalized = routeEntry.relativePath.split(path.sep).join("/");
  const stem = normalized.slice(0, -4);
  const segments = stem.split("/");
  if (segments.at(-1) === "index") {
    segments.pop();
  }

  const routeSegments = segments
    .filter((segment) => segment.length > 0)
    .map((segment) => {
      if (segment.startsWith("[") && segment.endsWith("]") && segment.length > 2) {
        return `{${segment.slice(1, -1)}}`;
      }
      return segment;
    });
  return routeSegments.length === 0 ? "/" : `/${routeSegments.join("/")}`;
}

function buildInlineRustPrefix({ routePath }) {
  const lines = [
    "// AUTOGENERATED by thebe — inline Rust view",
    "#![allow(unused_attributes, dead_code, private_interfaces)]",
    `const __ROUTE_PATH: &str = ${JSON.stringify(routePath)};`,
    "",
  ];
  return `${lines.join("\n")}\n`;
}

function buildInlineRustSuffix() {
  const lines = [
    "",
    "type __ThebeResponse = Result<axum::response::Html<String>, axum::response::Response>;",
    "",
    "async fn __thebe_render_handler() -> __ThebeResponse {",
    "    todo!(\"inline Rust view render wrapper\");",
    "}",
    "",
    "pub fn router<S>() -> axum::Router<S>",
    "where",
    "    S: Clone + Send + Sync + 'static,",
    "{",
    "    axum::Router::<S>::new().route(",
    "        __ROUTE_PATH,",
    "        axum::routing::get(__thebe_render_handler),",
    "    )",
    "}",
    "",
  ];
  return lines.join("\n");
}

function mapSourceOffsetToInlineOffset({ sourceOffset, scriptBlock, prefixLength }) {
  if (typeof sourceOffset !== "number") {
    return prefixLength;
  }

  const clampedOffset = Math.min(Math.max(sourceOffset, scriptBlock.start), scriptBlock.end);
  return prefixLength + clampedOffset - scriptBlock.start;
}

function mapInlineOffsetToSourceOffset({ inlineOffset, view }) {
  if (typeof inlineOffset !== "number") {
    return null;
  }

  const contentLength = view.scriptEndOffset - view.scriptStartOffset;
  if (inlineOffset < view.prefixLength || inlineOffset > view.prefixLength + contentLength) {
    return null;
  }

  return view.scriptStartOffset + inlineOffset - view.prefixLength;
}

function resolveInlineRustSourceRange({ view, startOffset, endOffset }) {
  const sourceStartOffset = mapInlineOffsetToSourceOffset({ inlineOffset: startOffset, view });
  const sourceEndOffset = mapInlineOffsetToSourceOffset({ inlineOffset: endOffset, view });
  if (sourceStartOffset === null || sourceEndOffset === null) {
    return null;
  }

  return {
    startOffset: sourceStartOffset,
    endOffset: sourceEndOffset,
  };
}

function resolveInlineRustSourcePositionRange({ view, startOffset, endOffset }) {
  if (typeof view.sourceText !== "string") {
    return null;
  }

  const sourceRange = resolveInlineRustSourceRange({ view, startOffset, endOffset });
  if (!sourceRange) {
    return null;
  }

  return {
    start: positionAtOffset(view.sourceText, sourceRange.startOffset),
    end: positionAtOffset(view.sourceText, sourceRange.endOffset),
  };
}

function resolveInlineRustHandlerHover({
  documentPath,
  workspaceFolders,
  source,
  sourceOffset,
}) {
  if (typeof sourceOffset !== "number") {
    return null;
  }

  const routeEntry = resolveRouteSourceEntry({ documentPath, workspaceFolders });
  if (!routeEntry) {
    return null;
  }

  const scriptBlock = findRustSetupBlock(source);
  if (!scriptBlock) {
    return null;
  }

  if (sourceOffset < scriptBlock.start || sourceOffset > scriptBlock.end) {
    return null;
  }

  const handler = findRustRouteHandlerAtOffset(scriptBlock.content, sourceOffset - scriptBlock.start);
  if (!handler) {
    return null;
  }

  const routePath = resolveRoutePathPattern({ documentPath, workspaceFolders });
  const params = handler.paramTypes.length === 0 ? "none" : handler.paramTypes.join(", ");
  const state = handler.stateType ?? "none";
  return {
    contents: `**${handler.method} ${routePath}**\n\nHandler \`${handler.name}\`\n\n- Async: ${handler.isAsync ? "yes" : "no"}\n- Params: ${params}\n- State: ${state}`,
    startOffset: scriptBlock.start + handler.nameStartOffset,
    endOffset: scriptBlock.start + handler.nameEndOffset,
  };
}

function positionAtOffset(source, offset) {
  const targetOffset = Math.min(Math.max(offset, 0), source.length);
  let line = 0;
  let character = 0;

  for (let index = 0; index < targetOffset; index += 1) {
    const code = source.charCodeAt(index);
    if (code === 13) {
      if (source.charCodeAt(index + 1) === 10) {
        index += 1;
      }
      line += 1;
      character = 0;
      continue;
    }

    if (code === 10) {
      line += 1;
      character = 0;
      continue;
    }

    character += 1;
  }

  return { line, character };
}

function findRustRouteHandlerAtOffset(scriptSource, offset) {
  const handlerPattern = /((?:^\s*#\[[^\r\n]+\]\s*$\r?\n?)*)^\s*(?:pub\s+)?(?:(async)\s+)?fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(/gm;
  let match;
  while ((match = handlerPattern.exec(scriptSource)) !== null) {
    const attributeMatch = match[1].match(/#\[\s*thebe::([A-Za-z_][A-Za-z0-9_]*)\s*(?:\([^\]\r\n]*\))?\s*\]/m);
    if (!attributeMatch) {
      continue;
    }

    const openParenOffset = handlerPattern.lastIndex - 1;
    const closeParenOffset = findMatchingDelimiter(scriptSource, openParenOffset, "(", ")");
    if (closeParenOffset === -1) {
      continue;
    }

    const fnTokenOffset = match[0].lastIndexOf("fn");
    const nameOffsetInMatch = match[0].indexOf(match[3], fnTokenOffset);
    if (nameOffsetInMatch === -1) {
      continue;
    }

    const nameStartOffset = match.index + nameOffsetInMatch;
    const nameEndOffset = nameStartOffset + match[3].length;
    if (offset < nameStartOffset || offset > nameEndOffset) {
      continue;
    }

    const paramsSource = scriptSource.slice(openParenOffset + 1, closeParenOffset);
    const { paramTypes, stateType } = parseHandlerParameterTypes(paramsSource);
    return {
      method: attributeMatch[1].toUpperCase(),
      isAsync: Boolean(match[2]),
      name: match[3],
      nameStartOffset,
      nameEndOffset,
      paramTypes,
      stateType,
    };
  }

  return null;
}

function parseHandlerParameterTypes(paramsSource) {
  const paramTypes = [];
  let stateType = null;

  for (const segment of splitTopLevelSegments(paramsSource, ",")) {
    const trimmed = collapseWhitespace(segment);
    if (trimmed.length === 0) {
      continue;
    }

    const colonOffset = findTopLevelDelimiterIndex(trimmed, ":");
    const typeText = collapseWhitespace(colonOffset === -1 ? trimmed : trimmed.slice(colonOffset + 1));
    if (typeText.length === 0) {
      continue;
    }

    const extractedStateType = extractStateType(typeText);
    if (extractedStateType && !stateType) {
      stateType = collapseWhitespace(extractedStateType);
      continue;
    }

    paramTypes.push(typeText);
  }

  return {
    paramTypes,
    stateType,
  };
}

function splitTopLevelSegments(source, delimiter) {
  const segments = [];
  let segmentStart = 0;
  let angleDepth = 0;
  let parenDepth = 0;
  let bracketDepth = 0;
  let braceDepth = 0;

  for (let index = 0; index < source.length; index += 1) {
    const char = source[index];
    if (char === "<") {
      angleDepth += 1;
      continue;
    }
    if (char === ">") {
      angleDepth = Math.max(0, angleDepth - 1);
      continue;
    }
    if (char === "(") {
      parenDepth += 1;
      continue;
    }
    if (char === ")") {
      parenDepth = Math.max(0, parenDepth - 1);
      continue;
    }
    if (char === "[") {
      bracketDepth += 1;
      continue;
    }
    if (char === "]") {
      bracketDepth = Math.max(0, bracketDepth - 1);
      continue;
    }
    if (char === "{") {
      braceDepth += 1;
      continue;
    }
    if (char === "}") {
      braceDepth = Math.max(0, braceDepth - 1);
      continue;
    }

    if (
      char === delimiter
      && angleDepth === 0
      && parenDepth === 0
      && bracketDepth === 0
      && braceDepth === 0
    ) {
      segments.push(source.slice(segmentStart, index));
      segmentStart = index + 1;
    }
  }

  segments.push(source.slice(segmentStart));
  return segments;
}

function findTopLevelDelimiterIndex(source, delimiter) {
  let angleDepth = 0;
  let parenDepth = 0;
  let bracketDepth = 0;
  let braceDepth = 0;

  for (let index = 0; index < source.length; index += 1) {
    const char = source[index];
    if (char === "<") {
      angleDepth += 1;
      continue;
    }
    if (char === ">") {
      angleDepth = Math.max(0, angleDepth - 1);
      continue;
    }
    if (char === "(") {
      parenDepth += 1;
      continue;
    }
    if (char === ")") {
      parenDepth = Math.max(0, parenDepth - 1);
      continue;
    }
    if (char === "[") {
      bracketDepth += 1;
      continue;
    }
    if (char === "]") {
      bracketDepth = Math.max(0, bracketDepth - 1);
      continue;
    }
    if (char === "{") {
      braceDepth += 1;
      continue;
    }
    if (char === "}") {
      braceDepth = Math.max(0, braceDepth - 1);
      continue;
    }

    if (
      char === delimiter
      && angleDepth === 0
      && parenDepth === 0
      && bracketDepth === 0
      && braceDepth === 0
    ) {
      return index;
    }
  }

  return -1;
}

function findMatchingDelimiter(source, openOffset, openChar, closeChar) {
  let depth = 0;
  for (let index = openOffset; index < source.length; index += 1) {
    const char = source[index];
    if (char === openChar) {
      depth += 1;
      continue;
    }
    if (char === closeChar) {
      depth -= 1;
      if (depth === 0) {
        return index;
      }
    }
  }

  return -1;
}

function extractStateType(typeText) {
  const match = typeText.trim().match(/State\s*<([\s\S]+)>$/);
  return match ? match[1].trim() : null;
}

function collapseWhitespace(source) {
  return source.trim().replace(/\s+/g, " ");
}

function findRustSetupBlock(source) {
  if (typeof source !== "string" || source.length === 0) {
    return null;
  }

  let offset = 0;
  while (offset < source.length) {
    const openTagStart = source.indexOf("<script", offset);
    if (openTagStart === -1) {
      return null;
    }

    const openTagEnd = findTagEnd(source, openTagStart + 7);
    if (openTagEnd === -1) {
      return null;
    }

    const attrs = parseTagAttributes(source.slice(openTagStart, openTagEnd + 1));
    if (Object.hasOwn(attrs, "setup")) {
      const contentStart = openTagEnd + 1;
      const closeTagStart = source.indexOf("</script>", contentStart);
      if (closeTagStart === -1) {
        return null;
      }

      return {
        start: contentStart,
        end: closeTagStart,
        content: source.slice(contentStart, closeTagStart),
      };
    }

    offset = openTagEnd + 1;
  }

  return null;
}

function findTagEnd(source, startOffset) {
  let quote = null;
  for (let index = startOffset; index < source.length; index += 1) {
    const char = source[index];
    if (quote) {
      if (char === quote) {
        quote = null;
      }
      continue;
    }

    if (char === '"' || char === "'") {
      quote = char;
      continue;
    }

    if (char === ">") {
      return index;
    }
  }

  return -1;
}

function parseTagAttributes(tagSource) {
  const attrs = Object.create(null);
  let offset = tagSource.indexOf("script") + 6;
  while (offset < tagSource.length) {
    offset = skipWhitespace(tagSource, offset);
    const char = tagSource[offset];
    if (!char || char === ">" || char === "/") {
      break;
    }

    const nameStart = offset;
    while (offset < tagSource.length) {
      const current = tagSource[offset];
      if (/\s|=|>|\//.test(current)) {
        break;
      }
      offset += 1;
    }

    const name = tagSource.slice(nameStart, offset).toLowerCase();
    offset = skipWhitespace(tagSource, offset);
    let value = true;
    if (tagSource[offset] === "=") {
      offset += 1;
      offset = skipWhitespace(tagSource, offset);
      value = readAttributeValue(tagSource, offset);
      offset = value.nextOffset;
      value = value.value;
    }

    attrs[name] = typeof value === "string" ? value.toLowerCase() : value;
  }

  return attrs;
}

function readAttributeValue(source, startOffset) {
  const quote = source[startOffset];
  if (quote === '"' || quote === "'") {
    let offset = startOffset + 1;
    while (offset < source.length && source[offset] !== quote) {
      offset += 1;
    }
    return {
      value: source.slice(startOffset + 1, offset),
      nextOffset: offset + 1,
    };
  }

  let offset = startOffset;
  while (offset < source.length && !/\s|>/.test(source[offset])) {
    offset += 1;
  }
  return {
    value: source.slice(startOffset, offset),
    nextOffset: offset,
  };
}

function skipWhitespace(source, startOffset) {
  let offset = startOffset;
  while (offset < source.length && /\s/.test(source[offset])) {
    offset += 1;
  }
  return offset;
}

module.exports = {
  INLINE_RUST_COMMAND_ID,
  resolveGeneratedServerMirrorPath,
  resolveInlineRustHandlerHover,
  resolveInlineRustSourcePositionRange,
  resolveInlineRustSourceRange,
  resolveInlineRustView,
};
