use anyhow::Context;
use std::path::Path;

/// Scaffold a new minimal Thebe project.
pub fn run(name: &str) -> anyhow::Result<()> {
  let project_dir = Path::new(name);
  anyhow::ensure!(!project_dir.exists(), "directory `{name}` already exists");
  let package_name = package_name_for_project_dir(project_dir)?;

  std::fs::create_dir_all(project_dir.join("src").join("routes"))
    .context("failed to create project directories")?;

  std::fs::write(project_dir.join("Cargo.toml"), cargo_toml(&package_name))
    .context("failed to write Cargo.toml")?;

  std::fs::write(project_dir.join(".gitignore"), "/target\n/.thebe\n")
    .context("failed to write .gitignore")?;

  std::fs::write(project_dir.join("src").join("main.rs"), MAIN_RS)
    .context("failed to write src/main.rs")?;

  std::fs::write(
    project_dir.join("src").join("routes").join("index.trs"),
    EXAMPLE_TRS,
  )
  .context("failed to write src/routes/index.trs")?;

  std::fs::write(
    project_dir.join("app.html"),
    thebe_codegen::default_app_html(),
  )
  .context("failed to write app.html")?;

  println!("created `{name}`");
  println!("  run:  cd {name} && thebe dev");
  Ok(())
}

fn cargo_toml(name: &str) -> String {
  format!(
    r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = {{ version = "1", features = ["full"] }}
tower-http = {{ version = "0.6", features = ["fs"] }}
minijinja = "2"
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
{thebe_runtime_dependency}
ts-rs = "12"
"#,
    thebe_runtime_dependency = thebe_runtime_dependency(),
  )
}

fn package_name_for_project_dir(project_dir: &Path) -> anyhow::Result<String> {
  let file_name = project_dir
    .file_name()
    .and_then(std::ffi::OsStr::to_str)
    .context("project directory name must be valid UTF-8")?;

  let mut package_name = String::with_capacity(file_name.len());
  let mut previous_was_dash = false;

  for ch in file_name.chars() {
    let mapped = if ch.is_ascii_alphanumeric() {
      ch.to_ascii_lowercase()
    } else if ch == '-' || ch == '_' {
      ch
    } else {
      '-'
    };

    if mapped == '-' {
      if package_name.is_empty() || previous_was_dash {
        continue;
      }
      previous_was_dash = true;
      package_name.push(mapped);
      continue;
    }

    previous_was_dash = false;
    package_name.push(mapped);
  }

  while package_name.ends_with('-') {
    package_name.pop();
  }

  anyhow::ensure!(
    !package_name.is_empty(),
    "directory name `{}` does not produce a valid package name",
    project_dir.display()
  );

  if package_name
    .chars()
    .next()
    .is_some_and(|ch| !ch.is_ascii_alphabetic() && ch != '_')
  {
    package_name.insert_str(0, "app-");
  }

  Ok(package_name)
}

fn thebe_runtime_dependency() -> String {
  let local_runtime_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../thebe-runtime");

  if local_runtime_path.join("Cargo.toml").exists()
    && let Ok(canonical_path) = local_runtime_path.canonicalize()
  {
    return format!(
      "thebe-runtime = {{ path = \"{}\" }}",
      canonical_path.to_string_lossy().replace('\\', "/")
    );
  }

  format!("thebe-runtime = \"{}\"", env!("CARGO_PKG_VERSION"))
}

const MAIN_RS: &str = r#"#![allow(non_snake_case)]

// Route modules and hotpatch helpers are generated by `thebe dev`.
include!("../.thebe/server/routes.rs");
include!("../.thebe/hotpatch.rs");

#[tokio::main]
async fn main() {
  connect_thebe_hotpatch()
    .expect("hotpatch runtime handshake should succeed when enabled");

  let app = thebe_routes().fallback_service(tower_http::services::ServeDir::new("public"));

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000")
        .await
        .expect("failed to bind to port 3000");

    println!("thebe dev listening at http://localhost:3000");
    axum::serve(listener, app).await.expect("server error");
}
"#;

const EXAMPLE_TRS: &str = r#"<script setup>
struct Props {
    title: String,
    subtitle: String,
}

#[thebe::get]
pub fn handler() -> Props {
    Props {
        title: "Hello from Thebe!".to_string(),
        subtitle: "A compiler-driven Rust web framework.".to_string(),
    }
}
</script>

<h1>{{ title }}</h1>
<p>{{ subtitle }}</p>
"#;

#[cfg(test)]
mod tests {
  use super::run;
  use std::fs;
  use std::path::PathBuf;
  use std::time::{SystemTime, UNIX_EPOCH};

  use super::{package_name_for_project_dir, thebe_runtime_dependency};

  #[test]
  fn package_name_for_project_dir_should_sanitize_path_segments() {
    let project_dir = PathBuf::from("/tmp/123.Thebe Demo");

    let package_name = package_name_for_project_dir(&project_dir)
      .expect("package name sanitization should succeed");

    assert_eq!(package_name, "app-123-thebe-demo");
  }

  #[test]
  fn run_should_scaffold_a_hotpatch_ready_standalone_project() {
    let project_dir = temp_project_root("new.project");
    let project_name = project_dir.to_string_lossy().into_owned();
    let expected_package_name = package_name_for_project_dir(&project_dir)
      .expect("temp project path should yield a valid package name");

    run(&project_name).expect("project scaffold should succeed");

    let cargo_toml = fs::read_to_string(project_dir.join("Cargo.toml"))
      .expect("Cargo.toml should be written");
    assert!(cargo_toml.contains(&format!("name = \"{expected_package_name}\"")));
    assert!(cargo_toml.contains("version = \"0.1.0\""));
    assert!(!cargo_toml.contains("version.workspace = true"));
    assert!(cargo_toml.contains(&thebe_runtime_dependency()));

    let main_rs = fs::read_to_string(project_dir.join("src/main.rs"))
      .expect("src/main.rs should be written");
    assert!(main_rs.contains("include!(\"../.thebe/hotpatch.rs\");"));
    assert!(main_rs.contains("connect_thebe_hotpatch()"));

    let _ = fs::remove_dir_all(project_dir);
  }

  fn temp_project_root(test_name: &str) -> PathBuf {
    let unique_suffix = SystemTime::now()
      .duration_since(UNIX_EPOCH)
      .expect("clock should be after unix epoch")
      .as_nanos();
    std::env::temp_dir().join(format!("thebe-cli-{test_name}-{unique_suffix}"))
  }
}
