/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE_LBRACE = 1,
  anon_sym_RBRACE_RBRACE = 2,
  anon_sym_DOT = 3,
  sym_identifier = 4,
  anon_sym_LT = 5,
  anon_sym_script = 6,
  anon_sym_GT = 7,
  anon_sym_LT_SLASH = 8,
  anon_sym_style = 9,
  anon_sym_SLASH_GT = 10,
  sym_component_tag_name = 11,
  sym_html_tag_name = 12,
  anon_sym_EQ = 13,
  sym_attribute_name = 14,
  anon_sym_setup = 15,
  anon_sym_lang = 16,
  anon_sym_DQUOTEts_DQUOTE = 17,
  anon_sym_SQUOTEts_SQUOTE = 18,
  sym_double_quoted_attribute_value = 19,
  sym_single_quoted_attribute_value = 20,
  sym_unquoted_attribute_value = 21,
  sym_block_text = 22,
  sym_text = 23,
  sym_source_file = 24,
  sym_template_binding = 25,
  sym_binding_path = 26,
  sym_script_setup_element = 27,
  sym_script_ts_element = 28,
  sym_script_element = 29,
  sym_script_setup_start_tag = 30,
  sym_script_ts_start_tag = 31,
  sym_script_start_tag = 32,
  sym_script_end_tag = 33,
  sym_style_element = 34,
  sym_style_start_tag = 35,
  sym_style_end_tag = 36,
  sym_start_tag = 37,
  sym_end_tag = 38,
  sym_self_closing_tag = 39,
  sym_attribute = 40,
  sym_setup_attribute = 41,
  sym_lang_ts_attribute = 42,
  sym_raw_text = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_binding_path_repeat1 = 45,
  aux_sym_start_tag_repeat1 = 46,
  aux_sym_raw_text_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [anon_sym_LT] = "<",
  [anon_sym_script] = "html_tag_name",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_style] = "html_tag_name",
  [anon_sym_SLASH_GT] = "/>",
  [sym_component_tag_name] = "component_tag_name",
  [sym_html_tag_name] = "html_tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_setup] = "attribute_name",
  [anon_sym_lang] = "attribute_name",
  [anon_sym_DQUOTEts_DQUOTE] = "double_quoted_attribute_value",
  [anon_sym_SQUOTEts_SQUOTE] = "single_quoted_attribute_value",
  [sym_double_quoted_attribute_value] = "double_quoted_attribute_value",
  [sym_single_quoted_attribute_value] = "single_quoted_attribute_value",
  [sym_unquoted_attribute_value] = "unquoted_attribute_value",
  [sym_block_text] = "block_text",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_template_binding] = "template_binding",
  [sym_binding_path] = "binding_path",
  [sym_script_setup_element] = "script_setup_element",
  [sym_script_ts_element] = "script_ts_element",
  [sym_script_element] = "script_element",
  [sym_script_setup_start_tag] = "script_setup_start_tag",
  [sym_script_ts_start_tag] = "script_ts_start_tag",
  [sym_script_start_tag] = "script_start_tag",
  [sym_script_end_tag] = "script_end_tag",
  [sym_style_element] = "style_element",
  [sym_style_start_tag] = "style_start_tag",
  [sym_style_end_tag] = "style_end_tag",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_attribute] = "attribute",
  [sym_setup_attribute] = "setup_attribute",
  [sym_lang_ts_attribute] = "lang_ts_attribute",
  [sym_raw_text] = "raw_text",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_binding_path_repeat1] = "binding_path_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_raw_text_repeat1] = "raw_text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_script] = sym_html_tag_name,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_style] = sym_html_tag_name,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [sym_component_tag_name] = sym_component_tag_name,
  [sym_html_tag_name] = sym_html_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_setup] = sym_attribute_name,
  [anon_sym_lang] = sym_attribute_name,
  [anon_sym_DQUOTEts_DQUOTE] = sym_double_quoted_attribute_value,
  [anon_sym_SQUOTEts_SQUOTE] = sym_single_quoted_attribute_value,
  [sym_double_quoted_attribute_value] = sym_double_quoted_attribute_value,
  [sym_single_quoted_attribute_value] = sym_single_quoted_attribute_value,
  [sym_unquoted_attribute_value] = sym_unquoted_attribute_value,
  [sym_block_text] = sym_block_text,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_template_binding] = sym_template_binding,
  [sym_binding_path] = sym_binding_path,
  [sym_script_setup_element] = sym_script_setup_element,
  [sym_script_ts_element] = sym_script_ts_element,
  [sym_script_element] = sym_script_element,
  [sym_script_setup_start_tag] = sym_script_setup_start_tag,
  [sym_script_ts_start_tag] = sym_script_ts_start_tag,
  [sym_script_start_tag] = sym_script_start_tag,
  [sym_script_end_tag] = sym_script_end_tag,
  [sym_style_element] = sym_style_element,
  [sym_style_start_tag] = sym_style_start_tag,
  [sym_style_end_tag] = sym_style_end_tag,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_attribute] = sym_attribute,
  [sym_setup_attribute] = sym_setup_attribute,
  [sym_lang_ts_attribute] = sym_lang_ts_attribute,
  [sym_raw_text] = sym_raw_text,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_binding_path_repeat1] = aux_sym_binding_path_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_raw_text_repeat1] = aux_sym_raw_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_script] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_style] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_component_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_html_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_setup] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_lang] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTEts_DQUOTE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTEts_SQUOTE] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_block_text] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_template_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_binding_path] = {
    .visible = true,
    .named = true,
  },
  [sym_script_setup_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_ts_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_setup_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_ts_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_setup_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_lang_ts_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_binding_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_raw_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attribute = 1,
  field_name = 2,
  field_path = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attribute] = "attribute",
  [field_name] = "name",
  [field_path] = "path",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_name, 0},
  [3] =
    {field_attribute, 0},
  [4] =
    {field_attribute, 2},
    {field_name, 1},
  [6] =
    {field_attribute, 2, .inherited = true},
    {field_name, 1},
  [8] =
    {field_attribute, 0, .inherited = true},
    {field_attribute, 1, .inherited = true},
  [10] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 2,
        '\'', 9,
        '.', 41,
        '/', 15,
        '<', 43,
        '=', 67,
        '>', 46,
        'l', 51,
        's', 52,
        '{', 32,
        '}', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(50);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(75);
      if (lookahead == 's') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(75);
      if (lookahead == 't') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '/' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(77);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(73);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '>') ADVANCE(46);
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 's') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(76);
      if (lookahead == 's') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(76);
      if (lookahead == 't') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == '\'') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '\'') ADVANCE(74);
      END_STATE();
    case 12:
      if (lookahead == '\'') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == ':') ADVANCE(36);
      if (lookahead == '=') ADVANCE(67);
      if (lookahead == '>') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 14:
      if (lookahead == '<') ADVANCE(78);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(49);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(23);
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'g') ADVANCE(71);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(50);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 32:
      if (lookahead == '{') ADVANCE(39);
      END_STATE();
    case 33:
      if (lookahead == '}') ADVANCE(40);
      END_STATE();
    case 34:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(34);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(50);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 35:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 36:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      if (lookahead == '<') ADVANCE(43);
      if (lookahead == '{') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_script);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_script);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_style);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_component_tag_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'a') ADVANCE(58);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'c') ADVANCE(61);
      if (lookahead == 'e') ADVANCE(62);
      if (lookahead == 't') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'c') ADVANCE(61);
      if (lookahead == 't') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'g') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'i') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'l') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'n') ADVANCE(55);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'p') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'p') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'r') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 't') ADVANCE(64);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 't') ADVANCE(45);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'u') ADVANCE(59);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == 'y') ADVANCE(57);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_html_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_setup);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_setup);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_lang);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_lang);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_DQUOTEts_DQUOTE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_SQUOTEts_SQUOTE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_double_quoted_attribute_value);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_single_quoted_attribute_value);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_unquoted_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_block_text);
      if (lookahead == '/') ADVANCE(47);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_block_text);
      if (lookahead == '<') ADVANCE(78);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_block_text);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(39);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(83);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 37},
  [2] = {.lex_state = 37},
  [3] = {.lex_state = 37},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 37},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 37},
  [12] = {.lex_state = 37},
  [13] = {.lex_state = 37},
  [14] = {.lex_state = 37},
  [15] = {.lex_state = 37},
  [16] = {.lex_state = 37},
  [17] = {.lex_state = 37},
  [18] = {.lex_state = 13},
  [19] = {.lex_state = 37},
  [20] = {.lex_state = 37},
  [21] = {.lex_state = 37},
  [22] = {.lex_state = 37},
  [23] = {.lex_state = 37},
  [24] = {.lex_state = 37},
  [25] = {.lex_state = 37},
  [26] = {.lex_state = 13},
  [27] = {.lex_state = 37},
  [28] = {.lex_state = 26},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 13},
  [33] = {.lex_state = 14},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 14},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 14},
  [40] = {.lex_state = 34},
  [41] = {.lex_state = 35},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 14},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 14},
  [48] = {.lex_state = 14},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 35},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_script] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_style] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [sym_component_tag_name] = ACTIONS(1),
    [sym_html_tag_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_setup] = ACTIONS(1),
    [anon_sym_lang] = ACTIONS(1),
    [anon_sym_DQUOTEts_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTEts_SQUOTE] = ACTIONS(1),
    [sym_double_quoted_attribute_value] = ACTIONS(1),
    [sym_single_quoted_attribute_value] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(58),
    [sym_template_binding] = STATE(2),
    [sym_script_setup_element] = STATE(2),
    [sym_script_ts_element] = STATE(2),
    [sym_script_element] = STATE(2),
    [sym_script_setup_start_tag] = STATE(4),
    [sym_script_ts_start_tag] = STATE(5),
    [sym_script_start_tag] = STATE(6),
    [sym_style_element] = STATE(2),
    [sym_style_start_tag] = STATE(7),
    [sym_start_tag] = STATE(2),
    [sym_end_tag] = STATE(2),
    [sym_self_closing_tag] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LT_SLASH] = ACTIONS(9),
    [sym_text] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_SLASH,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_text,
    STATE(4), 1,
      sym_script_setup_start_tag,
    STATE(5), 1,
      sym_script_ts_start_tag,
    STATE(6), 1,
      sym_script_start_tag,
    STATE(7), 1,
      sym_style_start_tag,
    STATE(3), 9,
      sym_template_binding,
      sym_script_setup_element,
      sym_script_ts_element,
      sym_script_element,
      sym_style_element,
      sym_start_tag,
      sym_end_tag,
      sym_self_closing_tag,
      aux_sym_source_file_repeat1,
  [39] = 10,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(22), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(28), 1,
      sym_text,
    STATE(4), 1,
      sym_script_setup_start_tag,
    STATE(5), 1,
      sym_script_ts_start_tag,
    STATE(6), 1,
      sym_script_start_tag,
    STATE(7), 1,
      sym_style_start_tag,
    STATE(3), 9,
      sym_template_binding,
      sym_script_setup_element,
      sym_script_ts_element,
      sym_script_element,
      sym_style_element,
      sym_start_tag,
      sym_end_tag,
      sym_self_closing_tag,
      aux_sym_source_file_repeat1,
  [78] = 5,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      sym_block_text,
    STATE(11), 1,
      sym_script_end_tag,
    STATE(33), 1,
      aux_sym_raw_text_repeat1,
    STATE(42), 1,
      sym_raw_text,
  [94] = 5,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      sym_block_text,
    STATE(8), 1,
      sym_script_end_tag,
    STATE(33), 1,
      aux_sym_raw_text_repeat1,
    STATE(38), 1,
      sym_raw_text,
  [110] = 5,
    ACTIONS(31), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      sym_block_text,
    STATE(13), 1,
      sym_script_end_tag,
    STATE(33), 1,
      aux_sym_raw_text_repeat1,
    STATE(43), 1,
      sym_raw_text,
  [126] = 5,
    ACTIONS(33), 1,
      sym_block_text,
    ACTIONS(35), 1,
      anon_sym_LT_SLASH,
    STATE(12), 1,
      sym_style_end_tag,
    STATE(33), 1,
      aux_sym_raw_text_repeat1,
    STATE(49), 1,
      sym_raw_text,
  [142] = 2,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [152] = 5,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_setup,
    ACTIONS(45), 1,
      anon_sym_lang,
    STATE(52), 1,
      sym_setup_attribute,
    STATE(53), 1,
      sym_lang_ts_attribute,
  [168] = 5,
    ACTIONS(47), 1,
      anon_sym_GT,
    ACTIONS(49), 1,
      anon_sym_SLASH_GT,
    ACTIONS(51), 1,
      sym_attribute_name,
    STATE(18), 1,
      aux_sym_start_tag_repeat1,
    STATE(32), 1,
      sym_attribute,
  [184] = 2,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [194] = 2,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [204] = 2,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [214] = 2,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [224] = 2,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [234] = 2,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [244] = 2,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [254] = 5,
    ACTIONS(51), 1,
      sym_attribute_name,
    ACTIONS(81), 1,
      anon_sym_GT,
    ACTIONS(83), 1,
      anon_sym_SLASH_GT,
    STATE(26), 1,
      aux_sym_start_tag_repeat1,
    STATE(32), 1,
      sym_attribute,
  [270] = 2,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [280] = 2,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [290] = 2,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [300] = 2,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [310] = 2,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [320] = 2,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [330] = 2,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [340] = 4,
    ACTIONS(115), 1,
      sym_attribute_name,
    STATE(26), 1,
      aux_sym_start_tag_repeat1,
    STATE(32), 1,
      sym_attribute,
    ACTIONS(113), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [354] = 2,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 4,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [364] = 4,
    ACTIONS(122), 1,
      anon_sym_script,
    ACTIONS(124), 1,
      anon_sym_style,
    ACTIONS(126), 1,
      sym_component_tag_name,
    ACTIONS(128), 1,
      sym_html_tag_name,
  [377] = 2,
    ACTIONS(132), 1,
      anon_sym_EQ,
    ACTIONS(130), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [386] = 1,
    ACTIONS(134), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [392] = 3,
    ACTIONS(136), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(138), 1,
      anon_sym_DOT,
    STATE(36), 1,
      aux_sym_binding_path_repeat1,
  [402] = 1,
    ACTIONS(140), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [408] = 3,
    ACTIONS(142), 1,
      anon_sym_LT_SLASH,
    ACTIONS(144), 1,
      sym_block_text,
    STATE(35), 1,
      aux_sym_raw_text_repeat1,
  [418] = 3,
    ACTIONS(138), 1,
      anon_sym_DOT,
    ACTIONS(146), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(31), 1,
      aux_sym_binding_path_repeat1,
  [428] = 3,
    ACTIONS(148), 1,
      anon_sym_LT_SLASH,
    ACTIONS(150), 1,
      sym_block_text,
    STATE(35), 1,
      aux_sym_raw_text_repeat1,
  [438] = 3,
    ACTIONS(153), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(155), 1,
      anon_sym_DOT,
    STATE(36), 1,
      aux_sym_binding_path_repeat1,
  [448] = 1,
    ACTIONS(158), 3,
      sym_double_quoted_attribute_value,
      sym_single_quoted_attribute_value,
      sym_unquoted_attribute_value,
  [454] = 2,
    ACTIONS(160), 1,
      anon_sym_LT_SLASH,
    STATE(21), 1,
      sym_script_end_tag,
  [461] = 1,
    ACTIONS(162), 2,
      anon_sym_LT_SLASH,
      sym_block_text,
  [466] = 1,
    ACTIONS(164), 2,
      sym_component_tag_name,
      sym_html_tag_name,
  [471] = 2,
    ACTIONS(166), 1,
      sym_identifier,
    STATE(55), 1,
      sym_binding_path,
  [478] = 2,
    ACTIONS(160), 1,
      anon_sym_LT_SLASH,
    STATE(20), 1,
      sym_script_end_tag,
  [485] = 2,
    ACTIONS(160), 1,
      anon_sym_LT_SLASH,
    STATE(22), 1,
      sym_script_end_tag,
  [492] = 1,
    ACTIONS(153), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
  [497] = 1,
    ACTIONS(168), 2,
      anon_sym_LT_SLASH,
      sym_block_text,
  [502] = 1,
    ACTIONS(170), 2,
      anon_sym_DQUOTEts_DQUOTE,
      anon_sym_SQUOTEts_SQUOTE,
  [507] = 1,
    ACTIONS(172), 2,
      anon_sym_LT_SLASH,
      sym_block_text,
  [512] = 1,
    ACTIONS(174), 2,
      anon_sym_LT_SLASH,
      sym_block_text,
  [517] = 2,
    ACTIONS(176), 1,
      anon_sym_LT_SLASH,
    STATE(23), 1,
      sym_style_end_tag,
  [524] = 1,
    ACTIONS(178), 1,
      anon_sym_GT,
  [528] = 1,
    ACTIONS(180), 1,
      anon_sym_GT,
  [532] = 1,
    ACTIONS(182), 1,
      anon_sym_GT,
  [536] = 1,
    ACTIONS(184), 1,
      anon_sym_GT,
  [540] = 1,
    ACTIONS(186), 1,
      anon_sym_EQ,
  [544] = 1,
    ACTIONS(188), 1,
      anon_sym_RBRACE_RBRACE,
  [548] = 1,
    ACTIONS(190), 1,
      anon_sym_GT,
  [552] = 1,
    ACTIONS(192), 1,
      anon_sym_GT,
  [556] = 1,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
  [560] = 1,
    ACTIONS(196), 1,
      anon_sym_style,
  [564] = 1,
    ACTIONS(198), 1,
      anon_sym_GT,
  [568] = 1,
    ACTIONS(200), 1,
      sym_identifier,
  [572] = 1,
    ACTIONS(202), 1,
      anon_sym_GT,
  [576] = 1,
    ACTIONS(204), 1,
      anon_sym_script,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 110,
  [SMALL_STATE(7)] = 126,
  [SMALL_STATE(8)] = 142,
  [SMALL_STATE(9)] = 152,
  [SMALL_STATE(10)] = 168,
  [SMALL_STATE(11)] = 184,
  [SMALL_STATE(12)] = 194,
  [SMALL_STATE(13)] = 204,
  [SMALL_STATE(14)] = 214,
  [SMALL_STATE(15)] = 224,
  [SMALL_STATE(16)] = 234,
  [SMALL_STATE(17)] = 244,
  [SMALL_STATE(18)] = 254,
  [SMALL_STATE(19)] = 270,
  [SMALL_STATE(20)] = 280,
  [SMALL_STATE(21)] = 290,
  [SMALL_STATE(22)] = 300,
  [SMALL_STATE(23)] = 310,
  [SMALL_STATE(24)] = 320,
  [SMALL_STATE(25)] = 330,
  [SMALL_STATE(26)] = 340,
  [SMALL_STATE(27)] = 354,
  [SMALL_STATE(28)] = 364,
  [SMALL_STATE(29)] = 377,
  [SMALL_STATE(30)] = 386,
  [SMALL_STATE(31)] = 392,
  [SMALL_STATE(32)] = 402,
  [SMALL_STATE(33)] = 408,
  [SMALL_STATE(34)] = 418,
  [SMALL_STATE(35)] = 428,
  [SMALL_STATE(36)] = 438,
  [SMALL_STATE(37)] = 448,
  [SMALL_STATE(38)] = 454,
  [SMALL_STATE(39)] = 461,
  [SMALL_STATE(40)] = 466,
  [SMALL_STATE(41)] = 471,
  [SMALL_STATE(42)] = 478,
  [SMALL_STATE(43)] = 485,
  [SMALL_STATE(44)] = 492,
  [SMALL_STATE(45)] = 497,
  [SMALL_STATE(46)] = 502,
  [SMALL_STATE(47)] = 507,
  [SMALL_STATE(48)] = 512,
  [SMALL_STATE(49)] = 517,
  [SMALL_STATE(50)] = 524,
  [SMALL_STATE(51)] = 528,
  [SMALL_STATE(52)] = 532,
  [SMALL_STATE(53)] = 536,
  [SMALL_STATE(54)] = 540,
  [SMALL_STATE(55)] = 544,
  [SMALL_STATE(56)] = 548,
  [SMALL_STATE(57)] = 552,
  [SMALL_STATE(58)] = 556,
  [SMALL_STATE(59)] = 560,
  [SMALL_STATE(60)] = 564,
  [SMALL_STATE(61)] = 568,
  [SMALL_STATE(62)] = 572,
  [SMALL_STATE(63)] = 576,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_ts_element, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_ts_element, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_setup_element, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_setup_element, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_binding, 3, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_binding, 3, 0, 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 2),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 2),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 6),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 6),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 2),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_setup_element, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_setup_element, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_ts_element, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_ts_element, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 6),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 6),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_end_tag, 3, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_end_tag, 3, 0, 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 7),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 7), SHIFT_REPEAT(29),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_end_tag, 3, 0, 2),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_end_tag, 3, 0, 2),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 8),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding_path, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 1, 0, 4),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_text, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding_path, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_raw_text_repeat1, 2, 0, 0),
  [150] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_raw_text_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_binding_path_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_path_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_start_tag, 3, 0, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_start_tag, 3, 0, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_setup_start_tag, 4, 0, 5),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_ts_start_tag, 4, 0, 5),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setup_attribute, 1, 0, 3),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [194] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lang_ts_attribute, 3, 0, 8),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_thebe(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "thebe",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
