#![allow(non_snake_case)]

// Route modules and __thebe_router() are generated by `thebe dev`.
include!("__thebe_routes.rs");

#[tokio::main]
async fn main() {
    let app = __thebe_router();

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000")
        .await
        .expect("failed to bind to port 3000");

    println!("thebe dev listening at http://localhost:3000");
    axum::serve(listener, app).await.expect("server error");
}
