use crate::{error::CodegenError, template};
use thebe_parser::SfcBlocks;

/// Metadata the CLI provides about a discovered route file.
pub struct RouteEntry {
    /// The Rust module name (e.g. `"index"`, `"about"`).
    pub mod_name: String,
    /// The Axum route path (e.g. `"/"`, `"/about"`).
    pub route_path: String,
}

/// Generate the Rust source code for a single route module.
///
/// The output is a complete, self-contained `.rs` file that:
/// 1. Pastes the `<script setup>` content verbatim (stripping `#[thebe::]` attrs).
/// 2. Emits an `async fn __thebe_render_handler()` that calls the user's handler.
/// 3. Emits a `pub fn router() -> axum::Router` that wires up the route.
pub fn generate_route(
    blocks: &SfcBlocks,
    route_path: &str,
) -> Result<String, CodegenError> {
    let setup = blocks
        .script_setup
        .as_deref()
        .ok_or(CodegenError::MissingScriptSetup)?;

    let setup_clean = strip_thebe_attrs(setup);
    let handler_name = find_handler_name(setup).ok_or(CodegenError::MissingHandler)?;
    let is_async = is_handler_async(setup, &handler_name);

    let template_parts = template::parse_template(&blocks.template)?;
    let html_builder = template::generate_html_builder(&template_parts);

    let handler_call = if is_async {
        format!("    let __props = {handler_name}().await;\n")
    } else {
        format!("    let __props = {handler_name}();\n")
    };

    let mut source = String::new();
    source.push_str("// AUTOGENERATED by thebe \u{2014} do not edit\n");
    source.push_str(&setup_clean);
    source.push_str("\n\n");
    source.push_str(
        "async fn __thebe_render_handler() -> axum::response::Html<String> {\n",
    );
    source.push_str(&handler_call);
    source.push_str(&html_builder);
    source.push_str("    axum::response::Html(__html)\n");
    source.push_str("}\n\n");
    source.push_str("pub fn router() -> axum::Router {\n");
    source.push_str("    axum::Router::new().route(\n");
    source.push_str(&format!("        \"{route_path}\",\n"));
    source.push_str("        axum::routing::get(__thebe_render_handler),\n");
    source.push_str("    )\n");
    source.push_str("}\n");

    Ok(source)
}

/// Generate the `src/main.rs` that ties all route modules together.
pub fn generate_main(routes: &[RouteEntry]) -> String {
    let mut source = String::new();
    source.push_str("// AUTOGENERATED by thebe \u{2014} do not edit\n");
    source.push_str("mod routes {\n");
    for route in routes {
        source.push_str(&format!("    pub mod {};\n", route.mod_name));
    }
    source.push_str("}\n\n");
    source.push_str("#[tokio::main]\n");
    source.push_str("async fn main() {\n");
    source.push_str("    let app = axum::Router::new()\n");
    for route in routes {
        source.push_str(&format!(
            "        .merge(routes::{}::router())\n",
            route.mod_name
        ));
    }
    source.push_str("    ;\n\n");
    source.push_str(
        "    let listener = tokio::net::TcpListener::bind(\"0.0.0.0:3000\")\n",
    );
    source.push_str("        .await\n");
    source.push_str("        .expect(\"failed to bind to port 3000\");\n\n");
    source.push_str(
        "    println!(\"thebe dev listening at http://localhost:3000\");\n",
    );
    source.push_str(
        "    axum::serve(listener, app).await.expect(\"server error\");\n",
    );
    source.push_str("}\n");

    source
}

/// Remove lines that consist solely of `#[thebe::...]` attributes.
fn strip_thebe_attrs(code: &str) -> String {
    code.lines()
        .filter(|line| {
            let t = line.trim();
            // Keep the line unless it's purely a #[thebe::] attribute.
            !(t.starts_with("#[thebe::") && t.ends_with(']'))
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Find the name of the function annotated with `#[thebe::<method>]`.
fn find_handler_name(setup: &str) -> Option<String> {
    let mut after_thebe_attr = false;

    for line in setup.lines() {
        let t = line.trim();

        if t.starts_with("#[thebe::") {
            after_thebe_attr = true;
            continue;
        }

        if after_thebe_attr {
            // Scan for `fn <name>` on this line, skipping `pub` / `async`.
            if let Some(fn_pos) = t.find("fn ") {
                let rest = &t[fn_pos + 3..];
                let name: String = rest
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '_')
                    .collect();
                if !name.is_empty() {
                    return Some(name);
                }
            }
            // Allow other attribute lines between the thebe attr and the fn.
            if !t.is_empty() && !t.starts_with('#') {
                after_thebe_attr = false;
            }
        }
    }
    None
}

/// Return `true` if the named handler function is declared `async`.
fn is_handler_async(setup: &str, handler_name: &str) -> bool {
    let pattern = format!("async fn {handler_name}");
    setup.contains(&pattern)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strip_thebe_attrs_removes_attr_lines() {
        let input = "#[thebe::get]\npub fn handler() -> Props { todo!() }";
        let result = strip_thebe_attrs(input);
        assert!(!result.contains("#[thebe::get]"));
        assert!(result.contains("pub fn handler()"));
    }

    #[test]
    fn find_handler_name_detects_sync_fn() {
        let setup = "#[thebe::get]\npub fn my_handler() -> Props { todo!() }";
        assert_eq!(find_handler_name(setup).as_deref(), Some("my_handler"));
    }

    #[test]
    fn find_handler_name_detects_async_fn() {
        let setup = "#[thebe::post]\npub async fn submit() -> Props { todo!() }";
        assert_eq!(find_handler_name(setup).as_deref(), Some("submit"));
    }

    #[test]
    fn find_handler_name_returns_none_when_missing() {
        let setup = "pub fn helper() {}";
        assert!(find_handler_name(setup).is_none());
    }
}
