use crate::{error::CodegenError, template};
use thebe_parser::SfcBlocks;

/// The thebe-client runtime JS, compiled into the binary at build time.
///
/// Every generated route embeds this verbatim into the served HTML so no
/// external CDN or npm install is required during `thebe dev`.
const THEBE_CLIENT_RUNTIME: &str =
    include_str!("../../../packages/thebe-client/runtime.js");

/// Metadata the CLI provides about a discovered route file.
pub struct RouteEntry {
    /// The Rust module name (e.g. `"index"`, `"about"`).
    pub mod_name: String,
    /// The Axum route path (e.g. `"/"`, `"/about"`).
    pub route_path: String,
}

/// Generate the Rust source code for a single route module.
///
/// The output is a complete, self-contained `.rs` file that:
/// 1. Injects `#[derive(serde::Serialize)]` on the `Props` struct.
/// 2. Pastes the `<script setup>` content (stripping `#[thebe::]` attrs).
/// 3. Stores the raw template as a `const` string.
/// 4. Embeds the thebe-client runtime JS and the processed `<script lang="ts">`
///    as `const` strings.
/// 5. Emits `__thebe_render_handler` that calls the handler, renders the
///    template at runtime via `minijinja`, injects the serialised Props JSON,
///    and returns an `axum::response::Html<String>` with client scripts.
/// 6. Emits `router()` that wires up the Axum route.
pub fn generate_route(
    blocks: &SfcBlocks,
    route_path: &str,
) -> Result<String, CodegenError> {
    let setup = blocks
        .script_setup
        .as_deref()
        .ok_or(CodegenError::MissingScriptSetup)?;

    // Validate the template before committing to codegen.
    template::parse_template(&blocks.template)?;

    let setup_clean = strip_thebe_attrs(setup);
    let setup_with_serde = inject_serde_derive(&setup_clean);
    let handler_name = find_handler_name(setup).ok_or(CodegenError::MissingHandler)?;
    let is_async = is_handler_async(setup, &handler_name);

    let handler_call = if is_async {
        format!("    let __props = {handler_name}().await;\n")
    } else {
        format!("    let __props = {handler_name}();\n")
    };

    let template_with_markers = template::inject_hydration_markers(&blocks.template);
    let template_literal = escape_rust_raw_str(&template_with_markers);

    // Process the optional `<script lang="ts">` block.
    let client_js = blocks
        .script_ts
        .as_deref()
        .map(|ts| {
            thebe_analyzer::analyze(ts)
                .map(|m| m.js)
                .unwrap_or_default()
        })
        .unwrap_or_default();
    let runtime_literal = escape_rust_raw_str(THEBE_CLIENT_RUNTIME);
    let client_script_literal = escape_rust_raw_str(&client_js);

    let mut source = String::new();
    source.push_str("// AUTOGENERATED by thebe \u{2014} do not edit\n");
    source.push_str("use serde::Serialize;\n\n");
    source.push_str(&setup_with_serde);
    source.push_str("\n\n");
    // Store the template and client scripts as compile-time constants.
    source.push_str(&format!("const __TEMPLATE: &str = {template_literal};\n"));
    source.push_str(&format!(
        "const __CLIENT_RUNTIME: &str = {runtime_literal};\n"
    ));
    source.push_str(&format!(
        "const __CLIENT_SCRIPT: &str = {client_script_literal};\n\n"
    ));
    source.push_str(
        "async fn __thebe_render_handler() -> axum::response::Html<String> {\n",
    );
    source.push_str(&handler_call);
    // Serialise Props to JSON (panics on serialisation failure — a programmer error).
    source.push_str(
        "    let __ctx = serde_json::to_value(&__props)\
         .expect(\"Props serialisation error\");\n",
    );
    // Render template at runtime via minijinja.
    source.push_str("    let __body = {\n");
    source.push_str("        use minijinja::Environment;\n");
    source.push_str("        let mut env = Environment::new();\n");
    source.push_str(
        "        env.add_template(\"__page\", __TEMPLATE)\
         .expect(\"template compile error\");\n",
    );
    source.push_str(
        "        env.get_template(\"__page\")\
         .expect(\"template not found\")\n",
    );
    source.push_str(
        "            .render(&__ctx)\
         .expect(\"template render error\")\n",
    );
    source.push_str("    };\n");
    // Inject the Props JSON and client scripts into the HTML shell.
    source.push_str("    let __props_json = __ctx.to_string();\n");
    source.push_str("    let __html = format!(\n");
    source.push_str(
        "        \"<!DOCTYPE html>\\n\\
         <html>\\n\\
         <body>\\n\\
         {body}\\n\\
         <script id=\\\"__thebe_props\\\" type=\\\"application/json\\\">{props_json}</script>\\n\\
         <script>{runtime}</script>\\n\\
         <script>{user_script}</script>\\n\\
         </body>\\n\\
         </html>\",\n",
    );
    source.push_str("        body = __body,\n");
    source.push_str("        props_json = __props_json,\n");
    source.push_str("        runtime = __CLIENT_RUNTIME,\n");
    source.push_str("        user_script = __CLIENT_SCRIPT,\n");
    source.push_str("    );\n");
    source.push_str("    axum::response::Html(__html)\n");
    source.push_str("}\n\n");
    source.push_str("pub fn router() -> axum::Router {\n");
    source.push_str("    axum::Router::new().route(\n");
    source.push_str(&format!("        \"{route_path}\",\n"));
    source.push_str("        axum::routing::get(__thebe_render_handler),\n");
    source.push_str("    )\n");
    source.push_str("}\n");

    Ok(source)
}

/// Generate the `src/main.rs` that ties all route modules together.
pub fn generate_main(routes: &[RouteEntry]) -> String {
    let mut source = String::new();
    source.push_str("// AUTOGENERATED by thebe \u{2014} do not edit\n");
    source.push_str("mod routes {\n");
    for route in routes {
        source.push_str(&format!("    pub mod {};\n", route.mod_name));
    }
    source.push_str("}\n\n");
    source.push_str("#[tokio::main]\n");
    source.push_str("async fn main() {\n");
    source.push_str("    let app = axum::Router::new()\n");
    for route in routes {
        source.push_str(&format!(
            "        .merge(routes::{}::router())\n",
            route.mod_name
        ));
    }
    source.push_str("    ;\n\n");
    source.push_str(
        "    let listener = tokio::net::TcpListener::bind(\"0.0.0.0:3000\")\n",
    );
    source.push_str("        .await\n");
    source.push_str("        .expect(\"failed to bind to port 3000\");\n\n");
    source.push_str(
        "    println!(\"thebe dev listening at http://localhost:3000\");\n",
    );
    source.push_str(
        "    axum::serve(listener, app).await.expect(\"server error\");\n",
    );
    source.push_str("}\n");

    source
}

/// Inject `#[derive(serde::Serialize)]` immediately before every `struct Props`
/// definition that does not already carry the attribute.
fn inject_serde_derive(code: &str) -> String {
    let lines: Vec<&str> = code.lines().collect();
    let mut out = String::new();

    for (i, &line) in lines.iter().enumerate() {
        let trimmed = line.trim();
        // Detect `struct Props` declarations.
        if trimmed.starts_with("struct Props") || trimmed.starts_with("pub struct Props") {
            // Check the preceding lines for an existing serde derive.
            let already_derived = lines[..i].iter().rev().take(5).any(|prev| {
                prev.trim().contains("serde::Serialize")
                    || prev.trim().contains("Serialize")
            });
            if !already_derived {
                out.push_str("#[derive(serde::Serialize)]\n");
            }
        }
        out.push_str(line);
        out.push('\n');
    }

    // Strip trailing newline added by the loop — callers add their own.
    out.trim_end_matches('\n').to_owned()
}

/// Remove lines that consist solely of `#[thebe::...]` attributes.
fn strip_thebe_attrs(code: &str) -> String {
    code.lines()
        .filter(|line| {
            let t = line.trim();
            !(t.starts_with("#[thebe::") && t.ends_with(']'))
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Escape `template` so it can be embedded as a Rust raw string literal.
///
/// We use `r#"..."#` with enough hashes to survive any `"#` sequences in the
/// template.  A maximum of 16 hashes should be enough for any real HTML.
fn escape_rust_raw_str(template: &str) -> String {
    let mut max_run = 0usize;
    let bytes = template.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'"' {
            // Count consecutive '#' after the quote.
            let mut run = 0usize;
            i += 1;
            while i < bytes.len() && bytes[i] == b'#' {
                run += 1;
                i += 1;
            }
            if run > max_run {
                max_run = run;
            }
        } else {
            i += 1;
        }
    }
    let hashes = "#".repeat(max_run + 1);
    format!("r{hashes}\"{template}\"{hashes}")
}

/// Find the name of the function annotated with `#[thebe::<method>]`.
fn find_handler_name(setup: &str) -> Option<String> {
    let mut after_thebe_attr = false;

    for line in setup.lines() {
        let t = line.trim();

        if t.starts_with("#[thebe::") {
            after_thebe_attr = true;
            continue;
        }

        if after_thebe_attr {
            if let Some(fn_pos) = t.find("fn ") {
                let rest = &t[fn_pos + 3..];
                let name: String = rest
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '_')
                    .collect();
                if !name.is_empty() {
                    return Some(name);
                }
            }
            if !t.is_empty() && !t.starts_with('#') {
                after_thebe_attr = false;
            }
        }
    }
    None
}

/// Return `true` if the named handler function is declared `async`.
fn is_handler_async(setup: &str, handler_name: &str) -> bool {
    let pattern = format!("async fn {handler_name}");
    setup.contains(&pattern)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strip_thebe_attrs_removes_attr_lines() {
        let input = "#[thebe::get]\npub fn handler() -> Props { todo!() }";
        let result = strip_thebe_attrs(input);
        assert!(!result.contains("#[thebe::get]"));
        assert!(result.contains("pub fn handler()"));
    }

    #[test]
    fn find_handler_name_detects_sync_fn() {
        let setup = "#[thebe::get]\npub fn my_handler() -> Props { todo!() }";
        assert_eq!(find_handler_name(setup).as_deref(), Some("my_handler"));
    }

    #[test]
    fn find_handler_name_detects_async_fn() {
        let setup = "#[thebe::post]\npub async fn submit() -> Props { todo!() }";
        assert_eq!(find_handler_name(setup).as_deref(), Some("submit"));
    }

    #[test]
    fn find_handler_name_returns_none_when_missing() {
        let setup = "pub fn helper() {}";
        assert!(find_handler_name(setup).is_none());
    }

    #[test]
    fn inject_serde_derive_adds_attribute() {
        let code = "struct Props {\n    title: String,\n}";
        let result = inject_serde_derive(code);
        assert!(result.contains("#[derive(serde::Serialize)]"));
    }

    #[test]
    fn inject_serde_derive_skips_when_already_present() {
        let code = "#[derive(serde::Serialize)]\nstruct Props {\n    title: String,\n}";
        let result = inject_serde_derive(code);
        // Should appear exactly once, not twice.
        assert_eq!(result.matches("serde::Serialize").count(), 1);
    }

    #[test]
    fn escape_rust_raw_str_handles_plain_template() {
        let s = escape_rust_raw_str("<h1>{{ title }}</h1>");
        assert!(s.starts_with("r#\""));
        assert!(s.ends_with("\"#"));
        assert!(s.contains("{{ title }}"));
    }

    #[test]
    fn generate_route_embeds_client_runtime() {
        use thebe_parser::SfcBlocks;

        let blocks = SfcBlocks {
            script_setup: Some(
                "#[thebe::get]\npub fn handler() -> Props { Props { counter: 0 } }"
                    .to_owned(),
            ),
            script_ts: Some(
                "let props = getProps<Props>();\nfunction inc() { props.counter += 1; }"
                    .to_owned(),
            ),
            template: "<span>{{ counter }}</span>".to_owned(),
            ..SfcBlocks::default()
        };

        let src = generate_route(&blocks, "/").unwrap();

        // The generated source must contain both client consts.
        assert!(src.contains("__CLIENT_RUNTIME"), "runtime const missing");
        assert!(src.contains("__CLIENT_SCRIPT"), "user script const missing");

        // The format! call must reference both as named args.
        assert!(src.contains("runtime = __CLIENT_RUNTIME"));
        assert!(src.contains("user_script = __CLIENT_SCRIPT"));

        // The analyzer must have stripped the generic type parameter.
        assert!(!src.contains("getProps<Props>()"), "TS generics not stripped");
        assert!(src.contains("getProps()"), "stripped call missing");

        // Registration call must be appended.
        assert!(src.contains("__thebe_register(\"inc\", inc)"));
    }
}
